title: Aleksei Trubin, PhD
logo: /assets/img/headshot_circle.jpg
description: [LinkedIn](https://www.linkedin.com/in/aleksei-trubin/)
description: [RG](https://www.researchgate.net/profile/Aleksei-Trubin)
show_downloads: false
theme: jekyll-theme-minimal
